name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display greeting
        run: |
          echo "Job is complete !"

      - name: Verify Python syntax
        run: |
          python -c "import ast; ast.parse(open('test.py').read())" || exit 1
          echo "Python syntax OK"

      - name: Run static analysis (flake8)
        run: |
          pip install flake8
          flake8 test.py --count --select=E9,F63,F7,F82 --show-source --statistics || exit 1
          echo "Static analysis passed"

  docker-build:
    needs: code-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/github:latest
